RateMyAnimal/RateMyAnimal.Application/ViewModels/AnimalCategoryViewModels/AnimalCategoryViewModel.cs
namespace RateMyAnimal.Application.ViewModels
{
    public class AnimalCategoryViewModel
    {
        public int CategoryId { get; set; }
        public int AnimalId { get; set; }
    }
}

RateMyAnimal/RateMyAnimal.Application/ViewModels/AnimalViewModels/AnimalViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RateMyAnimal.Application.ViewModels
{
    public class AnimalViewModel
    {
        public int? Id { get; set; }
        public string Image { get; set; }
        public DateTime? Date { get; set; }

        [MinLength(1, ErrorMessage = "The Categories field must have at least one category.")]
        [MaxLength(3, ErrorMessage = "The Categories field must have a maximum three categories.")]
        public IEnumerable<int> Categories { get; set; }
    }
}

RateMyAnimal/RateMyAnimal.Application/ViewModels/CategoryViewModels/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RateMyAnimal.Application.ViewModels
{
    public class CategoryViewModel
    {
        public int? Id { get; set; }

        [MinLength(3, ErrorMessage = "The Description field must have at least 3 characters.")]
        [MaxLength(25, ErrorMessage = "The Description field must have less than 25 characters.")]
        public string Description { get; set; }
        public IEnumerable<AnimalCategoryViewModel> AnimalCategories { get; set; }
    }
}

RateMyAnimal/RateMyAnimal.Application/Controllers/AnimalController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using RateMyAnimal.Application.ViewModels;
using RateMyAnimal.Domain.Entities;
using RateMyAnimal.Domain.Interfaces;
using RateMyAnimal.Domain.Responses;

namespace RateMyAnimal.Application.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IAnimalService _animalService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public AnimalController(IAnimalService animalService, ICategoryService categoryService, IMapper mapper)
        {
            _animalService = animalService;
            _categoryService = categoryService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var response = await GetRandomAnimal();

            ViewBag.Categories = await GetDllCategories();
            return View("Index", response.Data);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = _mapper.Map<CommonResponse<AnimalViewModel>>(await _animalService.GetById(id));

            ViewBag.ReturnTo = "ZooList";
            ViewBag.Categories = await GetDllCategories();
            return View("Index", response.Data);
        }

        public async Task<IActionResult> CreateAnimal(AnimalViewModel animal)
        {
            Animal data = _mapper.Map<Animal>(animal);

            var response = _mapper.Map<CommonResponse<AnimalViewModel>>(await _animalService.Add(data));

            ViewBag.Categories = await GetDllCategories();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateAnimal(AnimalViewModel animal)
        {
            Animal data = _mapper.Map<Animal>(animal);

            var response = _mapper.Map<CommonResponse<AnimalViewModel>>(await _animalService.Update(data));

            return RedirectToAction("ZooIndex");
        }

        public async Task<IActionResult> ZooIndex()
        {
            var response = await GetDllCategories();

            return View("ZooIndex", response);
        }

        public async Task<IActionResult> GetAll(int? categoryId)
        {
            if (categoryId.HasValue)
                return await GetAllByIdCategory((int)categoryId);

            var response = await _animalService.GetAll(null);

            return PartialView("_SearchZooPartial", response.Data);
        }
        public async Task<IActionResult> GetAllByIdCategory(int categoryId)
        {
            var response = await _animalService.GetAllByIdCategory((int)categoryId);

            return PartialView("_SearchZooPartial", response.Data);
        }

        private async Task<CommonResponse<AnimalViewModel>> GetRandomAnimal()
        {
            return _mapper.Map<CommonResponse<AnimalViewModel>>(await _animalService.GetRandomAnimalImage());
        }

        private async Task<IEnumerable<CategoryViewModel>> GetDllCategories()
        {
            var response = _mapper.Map<CommonResponse<IEnumerable<CategoryViewModel>>>(await _categoryService.GetAll());
            return response.Data;
        }
    }
}

RateMyAnimal/RateMyAnimal.Application/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using RateMyAnimal.Application.ViewModels;
using RateMyAnimal.Domain.Entities;
using RateMyAnimal.Domain.Interfaces;
using RateMyAnimal.Domain.Responses;

namespace RateMyAnimal.Application.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public CategoryController(ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var response = _mapper.Map<CommonResponse<IEnumerable<CategoryViewModel>>>(await _categoryService.GetAll());

            return View("Index", response.Data);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Title = "Create Category";
            return View("EditCategory");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = _mapper.Map<CommonResponse<CategoryViewModel>>(await _categoryService.GetById(id));

            ViewBag.Title = "Edit Category";
            return View("EditCategory", response.Data);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var response = _mapper.Map<CommonResponse<CategoryViewModel>>(await _categoryService.Delete(id));

            if(response.Succeeded)
                return await Index();

            ViewBag.Error = response.Message;

            var r = _mapper.Map<CommonResponse<IEnumerable<CategoryViewModel>>>(await _categoryService.GetAll());
            return View("Index", r.Data);
        }

        public async Task<IActionResult> SaveCategory(CategoryViewModel category)
        {
            Category data = _mapper.Map<Category>(category);

            if (category.Id.HasValue)
                await _categoryService.Update(data);
            else
                await _categoryService.Add(data);

            return await Index();
        }
    }
}

RateMyAnimal/RateMyAnimal.Application/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using RateMyAnimal.Domain.Interfaces;

namespace RateMyAnimal.Application.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public HomeController(ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _categoryService.GetAllInclude(10);

            return View("Index", response.Data);
        }

        public IActionResult ComingSoon()
        {
            return View();
        }
    }
}

RateMyAnimal/RateMyAnimal.Application/Views/Animal/Index.cshtml
@model AnimalViewModel

@{
    string image = string.Format("data:image/jpeg;base64,{0}", @Model.Image);
    string action = ViewBag.ReturnTo == null ? "CreateAnimal" : "UpdateAnimal";
}

<div class="row justify-content-md-center">

    <div class="col-md-12 col-md-auto">
        <div class="row justify-content-md-center">
            <div class="col-md-2 mb-2">
                <input type="submit" class="btn btn-primary btn-custom-color" value="Skip Animal" onclick="location.href='@Url.Action("Index", "Animal")'"/>
            </div>
        </div>
    </div>

    <div class="col-md-5 col-md-auto">
        <img src="@image" class="animal-image" />
    </div>
    <div class="col-md-6 col-md-auto">
        <div class="col-md-6 col-md-auto">
            <h2>Rate This Animal</h2>

            <form asp-action="@action" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="Date" />
                <input type="hidden" asp-for="Image" />

                <div class="form-group">
                    <label asp-for="Categories" class="col-md-8 control-label fw-bold"></label>

                    <select asp-for="Categories" class="form-control col-md-8 dropDownMulti" multiple="multiple">
                        @foreach (CategoryViewModel c in ViewBag.Categories)
                        {
                            <option value="@c.Id">@c.Description</option>
                        }
                    </select>                    
                    <span asp-validation-for="Categories" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <div class="col-md-12 mt-3">
                        <input type="submit" class="btn btn-primary btn-custom-color w-100" value="Evaluate"/>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

RateMyAnimal/RateMyAnimal.Application/Views/Animal/ZooIndex.cshtml
@model IEnumerable<CategoryViewModel>

<div class="row justify-content-md-center">
    <div class="col-md-6 col-md-auto">

        <div class="col-md-6 col-md-auto">
            <label class="col-md-8 control-label fw-bold">Categories</label>
            <select class="form-control col-md-8" id="DdlCategory_id">
                <option value="null">All Categories</option>
                @foreach (CategoryViewModel c in @Model)
                {
                    <option value="@c.Id">@c.Description</option>
                }
            </select>
        </div>

        <div class="col-md-4 col-md-auto form-group">
            <div class="col-md-12 mt-3">
                <input type="submit" class="btn btn-primary btn-custom-color w-100" value="Search" onclick="animal.searchZoo()" />
            </div>
        </div>

        <div id="SearchZooPartial"></div>
    </div>
</div>

@section Scripts {
    <script src="~/js/Views/Animal/animal.js"></script>
}

RateMyAnimal/RateMyAnimal.Application/Views/Animal/_SearchZooPartial.cshtml
@model IEnumerable<Animal>

@if (@Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Animals
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width=10%>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    </td>
                    <td width=60%>
                        <img src="@string.Format("data:image/jpeg;base64,{0}", Convert.ToBase64String(@item.Image))" class="animal-image-table" />
                    </td>
                    <td width=30%>
                        <div>
                            @foreach (var c in item.AnimalCategories)
                            {
                                <span class="category-card">@c.Category.Description</span>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="col-md-12 col-md-auto mt-2">
        <span class="text-danger">- There are no records for this category.</span>
    </div>
}

RateMyAnimal/RateMyAnimal.Application/Views/Category/EditCategory.cshtml
@model CategoryViewModel

<div class="row justify-content-md-center">
    <div class="col-md-4 col-md-auto">
        <h2>@ViewBag.Title</h2>

        <form asp-action="SaveCategory" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Description" class="control-label fw-bold"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="col-md-12 mt-3">
                    <input type="submit" class="btn btn-primary btn-custom-color w-100" value="Save" />
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

RateMyAnimal/RateMyAnimal.Application/Views/Category/Index.cshtml
@model IEnumerable<CategoryViewModel>

<div class="row justify-content-md-center">
    <div class="col-md-6 col-md-auto">
        <input asp-action="Create" type="submit" class="btn btn-primary btn-custom-color" value="New Category" onclick="location.href='@Url.Action("Create", "Category")'"/>
        
        @if (@ViewBag.Error != null)
        {
            <div class="col-md-12 col-md-auto mt-2">
                <span class="text-danger">- @ViewBag.Error</span>
            </div>
        }

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Categories
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width=80%>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td width=20%>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RateMyAnimal/RateMyAnimal.Application/Views/Home/ComingSoon.cshtml
<h1>Coming Soon:</h1>
<p>Create new categories without having to leave the animal classification.</p>
<p>Remove ratings.</p>
<p>Unique categories.</p>
<p>Authentication.</p>
<p>Classification history in the “e-commerce” model.</p>
<p>More friendly theme.</p>

<h1>TO DO:</h1>
<p>Tests;</p>
<p>Docker: 2 containers, separate webApp;</p>
<p>Unavailable external service handling;</p>
<p>Concurrence handling;</p>
<p>Change base colors in Bootstrap;</p>
<p>ViewModels and calls refactoring;</p>
<p>Error handling;</p>
<p>Empty list handling;</p> 

RateMyAnimal/RateMyAnimal.Application/Views/Home/Index.cshtml
@model IEnumerable<Category>

<div class="row justify-content-md-center">
    <div class="col-md-3">
        <img src="~/images/paw.svg" class="paw-home" onclick="location.href='@Url.Action("Index", "Animal")'" />
    </div>
</div>

@if (Model != null)
{
    <div class="row justify-content-md-center">
        <div class="col-md-6 col-md-auto">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            <b>TOP</b> Categories
                        </th>
                        <th>Uses</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td width=80%>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td width=20%>
                                @item.AnimalCategories.Count()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

RateMyAnimal/RateMyAnimal.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RateMyAnimal</title>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #13383d">
            <div class="container-fluid" >
                <img src="~/images/paw.svg" class="paw-icon" />
                <a class="navbar-brand custom-color-text"asp-controller="Home" asp-action="Index">RateMyAnimal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                @await Html.PartialAsync("_NavBarPartial")
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RateMyAnimal/RateMyAnimal.Application/Views/Shared/_NavBarPartial.cshtml
<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">

        <li class="nav-item">
            <a class="nav-link custom-color-text" asp-controller="Animal" asp-action="Index">My Animals</a>
        </li>       
        
        <li class="nav-item">                    
            <a class="nav-link custom-color-text" asp-controller="Animal" asp-action="ZooIndex">Zoo</a>
        </li>

        <li class="nav-item">
            <a class="nav-link custom-color-text" asp-controller="Category" asp-action="Index">Manage Categories</a>
        </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <li class="nav-item">
            <a class="nav-link custom-color-text" asp-controller="Home" asp-action="ComingSoon">Coming soon...</a>
        </li>
    </ul>
</div>